// frontend-angular/src/app/components/app-layout/app-layout.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

import { TodosContainer } from '../todos-container/todos-container';
import { CreateTodo } from '../create-todo/create-todo';
import { ActiveTodoNumber } from '../active-todo-number/active-todo-number';

@Component({
  selector: 'app-app-layout',
  standalone: true,
  imports: [CommonModule, TodosContainer, CreateTodo, ActiveTodoNumber],
  templateUrl: './app-layout.html',
  styleUrls: ['./app-layout.css']
})
export class AppLayout {}

// frontend-react/src/components/AppLayout/AppLayout.jsx
import React from "react";
import ActiveTodoNumber from "../ActiveTodoNumber/ActiveTodoNumber";
import CreateTodo from "../CreateTodo/CreateTodo";
import TodosContainer from "../TodosContainer/TodosContainer";
import "./appLayout.css";

const AppLayout = () => {
  return (
    <div className="app-layout">
      <div className="left-side">
        <TodosContainer />
      </div>

      <div className="right-side">
        <CreateTodo />
        <ActiveTodoNumber />
      </div>
    </div>
  );
};

export default AppLayout;
