// frontend-angular/src/app/components/edit-todo-content/edit-todo-content.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TODO_STATUS_OPTIONS } from '../../config/todo-status-options';
import { TodoStatus, UpdateTodoInput } from '../../model/todo.model';

@Component({
  selector: 'app-edit-todo-content',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './edit-todo-content.html',
  styleUrls: ['./edit-todo-content.css']
})
export class EditTodoContent {

  @Input() title!: string;
  @Input() note: string = '';
  @Input() status!: TodoStatus;

  @Output() onCancel = new EventEmitter<void>();
  @Output() onUpdate = new EventEmitter<UpdateTodoInput>();

  editTitle = '';
  editNote = '';
  editStatus: TodoStatus = 'NEW';

  error = false;

  statusOptions = TODO_STATUS_OPTIONS;

  ngOnInit() {
    this.editTitle = this.title;
    this.editNote = this.note ?? '';
    this.editStatus = this.status;
  }

  handleUpdate() {
    if (!this.editTitle.trim()) {
      this.error = true;
      return;
    }

    this.error = false;

    const updatedTodo: UpdateTodoInput = {
      title: this.editTitle.trim(),
      note: this.editNote.trim(),
      status: this.editStatus
    };

    this.onUpdate.emit(updatedTodo);
  }

  handleCancel() {
    this.onCancel.emit();
  }
}

// frontend-react/src/components/EditTodoContent/EditTodoContent.jsx
import { useState } from "react";
import "./editTodoContent.css";
import { TODO_STATUS_OPTIONS } from "../../config/todoStatusOptions";

const EditTodoContent = ({ title, note, status, onCancel, onUpdate }) => {
  const [editTitle, setEditTitle] = useState(title);
  const [editNote, setEditNote] = useState(note || "");
  const [editStatus, setEditStatus] = useState(status);
  const [error, setError] = useState(false);

  const handleUpdate = () => {
    if (!editTitle.trim()) {
      setError(true);
      return;
    }

    setError(false);

    onUpdate({
      title: editTitle,
      note: editNote,
      status: editStatus
    });
  };

  return (
    <div className="edit-todo-container">

      <label className="edit-label">
        Title <span className="required">*</span>
      </label>
      <input
        type="text"
        className={`edit-input ${error ? "input-error" : ""}`}
        value={editTitle}
        onChange={(e) => {
          setEditTitle(e.target.value);
          if (error && e.target.value.trim() !== "") setError(false);
        }}
        placeholder="Enter title"
      />

      {error && <p className="error-text">Title is required.</p>}

      <label className="edit-label">Note</label>
      <textarea
        className="edit-textarea"
        rows={4}
        value={editNote}
        onChange={(e) => setEditNote(e.target.value)}
        placeholder="Enter note"
      />

      <label className="edit-label">Status</label>
      <select
        className="edit-select"
        value={editStatus}
        onChange={(e) => setEditStatus(e.target.value)}
      >
        {TODO_STATUS_OPTIONS.map((o) => (
          <option key={o.value} value={o.value}>
            {o.label}
          </option>
        ))}
      </select>

      <div className="edit-actions">
        <button className="edit-btn update-btn" onClick={handleUpdate}>
          Update
        </button>

        <button className="edit-btn cancel-btn" onClick={onCancel}>
          Cancel
        </button>
      </div>

    </div>
  );
};

export default EditTodoContent;
